/**
 * file: "app/layout.tsx"
 * description: arquivo responsavel pela renderização principal do React
 * data: 21/01/2024
 * author: Thiago Silva Andrade
 */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
// UI imports
import "./globals.css";
import { cn } from "@/lib/utils";

// VIEWS
import Navbar from "@/components/Navbar/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Natualmente Bom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" >
      <body className={cn("relative h-full font-sans antialiased", inter.className)}>
      <main className='relative flex flex-col min-h-screen'>
          <Providers>
            <Navbar />
            <div className='flex-grow flex-1'>
              {children}
            </div>
            
          </Providers>
        </main>
        {/* Exibição dos erros */}
        <Toaster  position="top-center" richColors/>
      </body>
    </html>
  );
}
